-- MySQL Script generated by MySQL Workbench
-- Tue Nov  9 21:33:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blue_bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blue_bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blue_bank` DEFAULT CHARACTER SET utf8 ;
USE `blue_bank` ;

-- -----------------------------------------------------
-- Table `blue_bank`.`dado_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_bank`.`dado_cliente` (
  `id_dados` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cpf` INT UNSIGNED NULL,
  `rua` VARCHAR(45) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `telefone` INT NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id_dados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blue_bank`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_bank`.`cliente` (
  `id_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NULL,
  `data_inicio` DATETIME NULL,
  `data_fim` DATETIME NULL,
  `dado_cliente_id_dados` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_dado_cliente1_idx` (`dado_cliente_id_dados` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_dado_cliente1`
    FOREIGN KEY (`dado_cliente_id_dados`)
    REFERENCES `blue_bank`.`dado_cliente` (`id_dados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blue_bank`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_bank`.`conta` (
  `id_conta` INT NOT NULL AUTO_INCREMENT,
  `nome_conta` VARCHAR(45) NULL,
  `data_abertura` DATETIME NULL,
  `data_fechamento` DATETIME NULL,
  `debito_bloqueado_sn` TINYINT NULL,
  `cliente_id_cliente` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_conta`),
  INDEX `fk_conta_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_conta_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `blue_bank`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blue_bank`.`agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_bank`.`agencia` (
  `id_agencia` INT NOT NULL,
  `nome_agencia` VARCHAR(45) NULL,
  `conta_id_conta` INT NOT NULL,
  PRIMARY KEY (`id_agencia`),
  INDEX `fk_agencia_conta_idx` (`conta_id_conta` ASC) VISIBLE,
  CONSTRAINT `fk_agencia_conta`
    FOREIGN KEY (`conta_id_conta`)
    REFERENCES `blue_bank`.`conta` (`id_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blue_bank`.`movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_bank`.`movimento` (
  `id_transacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_movimento` DATETIME NULL,
  `tipo_movimento` VARCHAR(45) NULL,
  `valor` INT NULL,
  `numero_doc` INT UNSIGNED NULL,
  `saldo` INT NULL,
  PRIMARY KEY (`id_transacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blue_bank`.`conta_has_movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_bank`.`conta_has_movimento` (
  `conta_id_conta` INT NOT NULL,
  `movimento_id_transacao` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`conta_id_conta`, `movimento_id_transacao`),
  INDEX `fk_conta_has_movimento_movimento1_idx` (`movimento_id_transacao` ASC) VISIBLE,
  INDEX `fk_conta_has_movimento_conta1_idx` (`conta_id_conta` ASC) VISIBLE,
  CONSTRAINT `fk_conta_has_movimento_conta1`
    FOREIGN KEY (`conta_id_conta`)
    REFERENCES `blue_bank`.`conta` (`id_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_has_movimento_movimento1`
    FOREIGN KEY (`movimento_id_transacao`)
    REFERENCES `blue_bank`.`movimento` (`id_transacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
