-- MySQL Script generated by MySQL Workbench
-- Wed Dec  8 20:55:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blue_bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blue_bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blue_bank` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `blue_bank` ;

-- -----------------------------------------------------
-- Table `blue_bank`.`agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_bank`.`agencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `status` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blue_bank`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_bank`.`conta` (
  `id_conta` INT NOT NULL AUTO_INCREMENT,
  `data_abertura` DATETIME NULL DEFAULT NULL,
  `data_fechamento` DATETIME NULL DEFAULT NULL,
  `debito_bloqueado` BIT(1) NULL DEFAULT NULL,
  `nome_conta` VARCHAR(255) NULL DEFAULT NULL,
  `saldo` DOUBLE NULL DEFAULT NULL,
  `age_id` INT NULL DEFAULT NULL,
  `agencia_id_agencia` INT NOT NULL,
  PRIMARY KEY (`id_conta`),
  INDEX `FKepvo588xh9unf87dlfngyfk1c` (`age_id` ASC) VISIBLE,
  INDEX `fk_conta_agencia_idx` (`agencia_id_agencia` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blue_bank`.`dado_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_bank`.`dado_usuario` (
  `id_dados` INT NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(255) NULL DEFAULT NULL,
  `cidade` VARCHAR(255) NULL DEFAULT NULL,
  `complemento` VARCHAR(255) NULL DEFAULT NULL,
  `cpf` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `numero` INT NULL DEFAULT NULL,
  `rua` VARCHAR(255) NULL DEFAULT NULL,
  `telefone` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_dados`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blue_bank`.`movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_bank`.`movimento` (
  `id_transacao` INT NOT NULL AUTO_INCREMENT,
  `data_movimento` DATE NULL DEFAULT NULL,
  `nome_terceiro` VARCHAR(255) NULL DEFAULT NULL,
  `numero_doc` INT NULL DEFAULT NULL,
  `tipo_movimento` VARCHAR(255) NULL DEFAULT NULL,
  `valor` DOUBLE NULL DEFAULT NULL,
  `conta_id_conta` INT NOT NULL,
  PRIMARY KEY (`id_transacao`),
  INDEX `fk_movimento_conta1_idx` (`conta_id_conta` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blue_bank`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blue_bank`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin` BIT(1) NULL DEFAULT NULL,
  `data_nascimento` DATETIME NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  `status` BIT(1) NULL DEFAULT NULL,
  `conta_id_conta` INT NOT NULL,
  `dado_usuario_id_dados` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_conta1_idx` (`conta_id_conta` ASC) VISIBLE,
  INDEX `fk_usuarios_dado_usuario1_idx` (`dado_usuario_id_dados` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
